auth_enabled: false

distributor:
  shard_by_all_labels: true
  ha_tracker:
    enable_ha_tracker: true
    kvstore:
      store: consul
      consul:
        host: consul:8500
  pool:
    health_check_ingesters: true
  ring:
    kvstore:
      store: memberlist

limits:
  accept_ha_samples: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip


ingester:
  lifecycler:
    # We want to start immediately.
    join_after: 0
    final_sleep: 0s
    num_tokens: 512

    ring:
      kvstore:
        store: memberlist
      replication_factor: 3

memberlist:
  join_members:
    - dns+cortex:7946
  abort_if_cluster_join_fails: false

store_gateway:
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist
    replication_factor: 1

storage:
  engine: blocks

blocks_storage:
  backend: s3

  tsdb:
    dir: /data/cortex-tsdb-ingester
    ship_interval: 1m
    block_ranges_period: [ 2h ]
    retention_period: 3h

  bucket_store:
    sync_dir: /data/cortex-tsdb-querier

  s3:
    endpoint:          minio:9000
    bucket_name:       cortex-tsdb
    access_key_id:     cortex
    secret_access_key: supersecret
    insecure:          true
